### ISSUE TITLE
initiate Rmarkdown website

### ISSUE THREAD

**Issue by bbest** [ecoquants/findinghal#2]
1. Create Rmd website following [10.5 rmarkdown’s site generator | R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html)
2. In `_site.yml` set output directory to same as input *.Rmd so get *.html in root folder (vs default of `_site/`):
  ```yaml
  output_dir: '.'
  ```
3. Create `.nojekyll` file (content free) to turn off Jekyll rendering (like we currently have for README.md), which speeds up time b/n commit-push and seeing website updated

**Comment by mspector13** [comment]
Hey @bbest, 

I created a _site.yml, index.Rmd, and about.Rmd files for our site, woohoo! I added the output_dir: '.' to _site.yml but I'm not sure if the line-spacing was conserved. 

Also, I assume that the `.nojekyll` file should be a plain-text file, right? When I tried to save a blank text file as ".nojekyll" I got the following error message from RStudio:

> Names that begin with a dot “.” are reserved for the system.
If you decide to go ahead and use a name which begins with a dot the file will be hidden.

To make sure this blank file didn't disapepar, I named it `content.nojekyll` What did I mess up?

**Comment by bbest** [comment]
Hi @mspector13,

In commit https://github.com/ecoquants/findinghal/commit/2004c85da8c6cf86f8585c0f7a18de71faa1a4f8, I just removed  `_Finding_Hal_site/` and used the **Build website** button to generate *.html into `.` per [`_site.yml`](https://github.com/ecoquants/findinghal/blob/main/_site.yml).

![image](https://user-images.githubusercontent.com/2837257/115904974-4b0a4000-a41a-11eb-96bb-83cc0f037e11.png)

That warning message about the "." for `.nojekyll` is fine.
