### ISSUE TITLE
Resize from readLines() for the Ab Key

### ISSUE THREAD

**Issue by mspector13** [ecoquants/findinghal#6]
Hey @bbest ,

I'm trying to figure out how to resize the still-under-construction abalone key to fit a window's size: 

<img width="560" alt="Screen Shot 2021-05-06 at 5 08 41 PM" src="https://user-images.githubusercontent.com/59982410/117380068-d0b3d400-ae8d-11eb-9d50-35e5316e66f3.png">

```{r, results="asis", warning=F}
cat(readLines("images/key.svg"))
```
From what I've read/seen, when you add in an image using 
`![some caption](./images/whatever_image.jpg)` the html output resizes the image to match a window's size, which is great!

However, it's easy enough to manually resize the image using `{width=n%}` (e.g. `(./images/whatever_image.jpg){width=75%}`) but I can't figure out how to make `readLines()` cooperate! No matter where I add `{width=n%}` I get error messages, such as:
<img width="602" alt="Screen Shot 2021-05-06 at 5 14 37 PM" src="https://user-images.githubusercontent.com/59982410/117380457-91d24e00-ae8e-11eb-87ef-d16ef36fdf89.png">

Instead of using cat(readLines) to add in the .svg key, should we just use `![some caption](./images/whatever_image.jpg)` ?

Thanks in advance!

**Comment by bbest** [comment]
Closing for now b/c going route of id cards #9
