### ISSUE TITLE
"resources.html" not loading correctly; but "Resources.html" is

### ISSUE THREAD

**Issue by mspector13** [ecoquants/findinghal#8]
Hey @bbest, 

As the title implies, I'm running into an issue with `resources.html`. Currently, [resources](https://findinghal.org/resources.html) won't load because of the lowercase R
<img width="667" alt="Screen Shot 2021-05-11 at 10 56 16 AM" src="https://user-images.githubusercontent.com/59982410/117863986-2ea73980-b249-11eb-9902-04671bacdbf3.png">

However, [Resources](https://findinghal.org/Resources.html) with a capitol R works just fine. 
<img width="692" alt="Screen Shot 2021-05-11 at 10 56 28 AM" src="https://user-images.githubusercontent.com/59982410/117864124-4ed6f880-b249-11eb-87da-595163e746b0.png">

In `_site.yml` I made sure that href calls resources.html, but this apparently isn't reflected online. 
<img width="438" alt="Screen Shot 2021-05-11 at 10 57 21 AM" src="https://user-images.githubusercontent.com/59982410/117864261-71691180-b249-11eb-9738-4ed104e898d0.png">

You'll be able to see several commits back that I changed `Resources.Rmd` to `resources.Rmd` to make sure that everything is inline. However, the "Resources" tab on [findinghal](findinghal.org) still points to the incorrect URL. 

Any idea what's going on? I'm sure it's something simple that I'm not seeing. 

Thanks!

**Comment by bbest** [comment]
Fixed with these commits:

* [Rename Resources.Rmd -> resources.Rmd; build all · ecoquants/findinghal@aeec342](https://github.com/ecoquants/findinghal/commit/aeec3424cc71894a8fa1534732ac1a6251028675)
* [∆ name Resources.Rmd · ecoquants/findinghal@b1f1c78](https://github.com/ecoquants/findinghal/commit/b1f1c780fcb3bc21a6ac802acf465cca89f12ad2)
